# Site settings
title: Travel Blog
email: nilsen@nstrands.com
description: Follow me
baseurl: "/travel-blog"
url: "http://nilsen.space"
twitter_username: @nhstrandskov
avatar: "https://pbs.twimg.com/profile_images/556295189439213569/_S-x5xhd_400x400.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Nilsen Strandskov" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
